version: '3.5'

services:

    distrodumper:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        volumes:
            - /localdir/torrents/:/dump
            - /home/user/.cache/distrodumper/:/cache
        environment:
            - "DISTRO_PREFIXES=archlinux,debian,manjaro,raspios"
            - DUMP_INTERVAL=3600
            - "FEED_URL=https://distrowatch.com/news/torrents.xml"
